window.HUMAN_CODING_EVENTS = [
  {
    "event_id": "E001",
    "family": "swe-bench",
    "from_version": "SWE-bench",
    "to_version": "SWE-bench Verified",
    "date": "2024-08-13",
    "capability_axis_change": "none",
    "morphology_change": "human-validated denoise (500 confirmed-solvable)",
    "saturation_driver": "unreliable_oracle",
    "source_url": "https://www.swebench.com/verified.html"
  },
  {
    "event_id": "E002",
    "family": "swe-bench",
    "from_version": "SWE-bench",
    "to_version": "SWE-bench Multimodal",
    "date": "2025-01-13",
    "capability_axis_change": "added_visual",
    "morphology_change": "screenshots/UI/diagrams",
    "saturation_driver": "capability_expansion",
    "source_url": "https://github.com/SWE-bench/SWE-bench"
  },
  {
    "event_id": "E003",
    "family": "swe-bench",
    "from_version": "SWE-bench",
    "to_version": "SWE-bench Live",
    "date": "2025-05-21",
    "capability_axis_change": "none",
    "morphology_change": "time-fresh tasks (created after 2024)",
    "saturation_driver": "contamination",
    "source_url": "https://github.com/microsoft/SWE-bench-Live"
  },
  {
    "event_id": "E004",
    "family": "swe-bench",
    "from_version": "SWE-bench Live",
    "to_version": "SWE-bench Live Verified",
    "date": "2025-07-19",
    "capability_axis_change": "none",
    "morphology_change": "LLM-filter + human verify",
    "saturation_driver": "quality_gate",
    "source_url": "https://github.com/microsoft/SWE-bench-Live"
  },
  {
    "event_id": "E005",
    "family": "swe-bench",
    "from_version": "SWE-bench Live Verified",
    "to_version": "SWE-bench Live monthly",
    "date": "2025-09-17",
    "capability_axis_change": "none",
    "morphology_change": "monthly +50 verified issues",
    "saturation_driver": "contamination",
    "source_url": "https://github.com/microsoft/SWE-bench-Live"
  },
  {
    "event_id": "E006",
    "family": "gaia",
    "from_version": "GAIA",
    "to_version": "GAIA2",
    "date": "2025",
    "capability_axis_change": "added_async_temporal_multiagent",
    "morphology_change": "dynamic asynchronous env (ARE) + write-action verifier",
    "saturation_driver": "static_qa_insufficient",
    "source_url": "https://openreview.net/forum?id=9gw03JpKK4"
  },
  {
    "event_id": "E007",
    "family": "gaia",
    "from_version": "GAIA",
    "to_version": "GAIA2",
    "date": "2025",
    "capability_axis_change": "added_ambiguity_tool-failure-recovery",
    "morphology_change": "clarification-requests + controlled tool failures",
    "saturation_driver": "robustness_gap",
    "source_url": "https://openreview.net/forum?id=9gw03JpKK4"
  },
  {
    "event_id": "E008",
    "family": "webarena",
    "from_version": "WebArena",
    "to_version": "VisualWebArena",
    "date": "2024-01-25",
    "capability_axis_change": "added_visual",
    "morphology_change": "image-text web tasks (910)",
    "saturation_driver": "capability_expansion",
    "source_url": "https://github.com/web-arena-x/visualwebarena"
  },
  {
    "event_id": "E009",
    "family": "webarena",
    "from_version": "WebArena",
    "to_version": "WorkArena",
    "date": "2024",
    "capability_axis_change": "enterprise_knowledge_work",
    "morphology_change": "enterprise web software tasks",
    "saturation_driver": "domain_expansion",
    "source_url": "https://arxiv.org/pdf/2412.05467"
  },
  {
    "event_id": "E010",
    "family": "webarena",
    "from_version": "WebArena",
    "to_version": "WebArena-Verified",
    "date": "2024-11-12",
    "capability_axis_change": "none",
    "morphology_change": "curated re-release",
    "saturation_driver": "reproducibility_gap",
    "source_url": "https://github.com/ServiceNow/webarena-verified"
  },
  {
    "event_id": "E011",
    "family": "tau-bench",
    "from_version": "tau-bench",
    "to_version": "tau2-bench",
    "date": "2025-06",
    "capability_axis_change": "added_dual_control",
    "morphology_change": "user can also call tools (telecom domain)",
    "saturation_driver": "single_control_unrealistic",
    "source_url": "https://arxiv.org/pdf/2506.07982"
  },
  {
    "event_id": "E012",
    "family": "tau-bench",
    "from_version": "tau2-bench",
    "to_version": "tau-Knowledge",
    "date": "2026",
    "capability_axis_change": "added_knowledge_retrieval",
    "morphology_change": "find info in doc corpora before acting",
    "saturation_driver": "policy-only_insufficient",
    "source_url": "https://github.com/sierra-research/tau2-bench"
  },
  {
    "event_id": "E013",
    "family": "tau-bench",
    "from_version": "tau2-bench",
    "to_version": "tau-Voice",
    "date": "2026",
    "capability_axis_change": "added_voice",
    "morphology_change": "full-duplex voice agents",
    "saturation_driver": "modality_expansion",
    "source_url": "https://github.com/sierra-research/tau2-bench"
  },
  {
    "event_id": "E014",
    "family": "tau-bench",
    "from_version": "tau2-bench",
    "to_version": "tau2 task-cleanup",
    "date": "2026",
    "capability_axis_change": "none",
    "morphology_change": "removed invalid actions/clarified/fixed loopholes",
    "saturation_driver": "oracle_errors",
    "source_url": "https://github.com/sierra-research/tau2-bench"
  },
  {
    "event_id": "E015",
    "family": "mmlu",
    "from_version": "MMLU",
    "to_version": "MMLU-Pro",
    "date": "2024-06",
    "capability_axis_change": "none",
    "morphology_change": "4->10 options + 12k graduate-level",
    "saturation_driver": "saturation_~86pct",
    "source_url": "https://arxiv.org/pdf/2406.01574"
  },
  {
    "event_id": "E016",
    "family": "mmlu",
    "from_version": "MMLU",
    "to_version": "MMLU-Redux",
    "date": "2024",
    "capability_axis_change": "none",
    "morphology_change": "3000 manual re-annotation",
    "saturation_driver": "annotation_noise",
    "source_url": "https://llm-stats.com/benchmarks/mmlu-redux"
  },
  {
    "event_id": "E017",
    "family": "mmlu",
    "from_version": "MMLU",
    "to_version": "GPQA",
    "date": "2024",
    "capability_axis_change": "harder_science",
    "morphology_change": "google-proof PhD-level (448)",
    "saturation_driver": "saturation",
    "source_url": "https://arxiv.org/pdf/2409.02257"
  },
  {
    "event_id": "E018",
    "family": "mmlu",
    "from_version": "MMLU-Pro",
    "to_version": "HLE/SuperGPQA",
    "date": "2025",
    "capability_axis_change": "harder_frontier",
    "morphology_change": "research-level manual questions",
    "saturation_driver": "saturation_~88pct",
    "source_url": "https://arxiv.org/pdf/2406.01574"
  },
  {
    "event_id": "E019",
    "family": "vqa",
    "from_version": "VQA",
    "to_version": "VQAv2",
    "date": "2017",
    "capability_axis_change": "none",
    "morphology_change": "balanced pairs to remove language priors",
    "saturation_driver": "language_prior_shortcut",
    "source_url": "https://arxiv.org/abs/1612.00837"
  },
  {
    "event_id": "E020",
    "family": "vqa",
    "from_version": "VQAv2",
    "to_version": "MMBench",
    "date": "2023",
    "capability_axis_change": "broad_multiskill",
    "morphology_change": "3200 MCQ + CircularEval order-bias control",
    "saturation_driver": "subjective_eval_noise",
    "source_url": "https://arxiv.org/abs/2307.06281"
  },
  {
    "event_id": "E021",
    "family": "vqa",
    "from_version": "MMBench",
    "to_version": "MMMU",
    "date": "2024",
    "capability_axis_change": "expert_reasoning",
    "morphology_change": "college-level 11.5k multi-discipline",
    "saturation_driver": "difficulty_insufficient",
    "source_url": "https://arxiv.org/abs/2311.16502"
  },
  {
    "event_id": "E022",
    "family": "vqa",
    "from_version": "MMMU",
    "to_version": "MMMU-Pro",
    "date": "2024",
    "capability_axis_change": "none",
    "morphology_change": "harder + vision-only shortcut removal",
    "saturation_driver": "saturation",
    "source_url": "https://arxiv.org/abs/2409.02813"
  },
  {
    "event_id": "E023",
    "family": "vqa",
    "from_version": "MMBench",
    "to_version": "NaturalBench",
    "date": "2024",
    "capability_axis_change": "vision_centric",
    "morphology_change": "reduce blind language-prior shortcuts",
    "saturation_driver": "blind_shortcut",
    "source_url": "https://arxiv.org/abs/2310.14566"
  },
  {
    "event_id": "E024",
    "family": "math",
    "from_version": "GSM8K",
    "to_version": "MATH",
    "date": "2021",
    "capability_axis_change": "harder_competition",
    "morphology_change": "competition-level 12.5k problems",
    "saturation_driver": "grade-school_too_easy",
    "source_url": "https://arxiv.org/abs/2103.03874"
  },
  {
    "event_id": "E025",
    "family": "math",
    "from_version": "MATH",
    "to_version": "AIME",
    "date": "2024",
    "capability_axis_change": "harder_olympiad",
    "morphology_change": "olympiad-style 30 problems",
    "saturation_driver": "saturation",
    "source_url": "https://llm-stats.com/benchmarks"
  },
  {
    "event_id": "E026",
    "family": "math",
    "from_version": "AIME",
    "to_version": "FrontierMath",
    "date": "2024",
    "capability_axis_change": "research_level",
    "morphology_change": "expert-vetted research math",
    "saturation_driver": "saturation",
    "source_url": "https://llm-stats.com/benchmarks"
  },
  {
    "event_id": "E027",
    "family": "math",
    "from_version": "GSM8K",
    "to_version": "GSM1K",
    "date": "2024",
    "capability_axis_change": "none",
    "morphology_change": "novel problems guaranteed unseen",
    "saturation_driver": "contamination_memorization",
    "source_url": "https://arxiv.org/abs/2405.00332"
  },
  {
    "event_id": "E028",
    "family": "math",
    "from_version": "GSM8K",
    "to_version": "GSM8K-Platinum",
    "date": "2025",
    "capability_axis_change": "none",
    "morphology_change": "noise-corrected revision",
    "saturation_driver": "annotation_noise",
    "source_url": "https://gradientscience.org/gsm8k-platinum/"
  },
  {
    "event_id": "E029",
    "family": "math",
    "from_version": "MATH",
    "to_version": "HLE",
    "date": "2025",
    "capability_axis_change": "research_level",
    "morphology_change": "manually authored research questions",
    "saturation_driver": "saturation",
    "source_url": "https://llm-stats.com/benchmarks"
  },
  {
    "event_id": "E030",
    "family": "safety",
    "from_version": "AdvBench",
    "to_version": "HarmBench",
    "date": "2024",
    "capability_axis_change": "none",
    "morphology_change": "standardized red-team + classifier ASR (510)",
    "saturation_driver": "inconsistent_eval_params",
    "source_url": "https://arxiv.org/abs/2402.04249"
  },
  {
    "event_id": "E031",
    "family": "safety",
    "from_version": "HarmBench",
    "to_version": "JailbreakBench",
    "date": "2024",
    "capability_axis_change": "added_overrefusal",
    "morphology_change": "dedup + 100 benign overrefusal controls",
    "saturation_driver": "duplicate_impossible_entries",
    "source_url": "https://jailbreakbench.github.io/"
  },
  {
    "event_id": "E032",
    "family": "safety",
    "from_version": "HarmBench",
    "to_version": "StrongREJECT",
    "date": "2024",
    "capability_axis_change": "none",
    "morphology_change": "313 prompts fixing earlier shortcomings",
    "saturation_driver": "weak_prompts",
    "source_url": "https://arxiv.org/abs/2402.10260"
  },
  {
    "event_id": "E033",
    "family": "safety",
    "from_version": "HarmBench",
    "to_version": "MM-SafetyBench",
    "date": "2024",
    "capability_axis_change": "added_multimodal",
    "morphology_change": "multimodal safety",
    "saturation_driver": "modality_expansion",
    "source_url": "https://www.evidentlyai.com/blog/llm-safety-bias-benchmarks"
  },
  {
    "event_id": "E034",
    "family": "safety",
    "from_version": "HarmBench",
    "to_version": "HELM-Safety",
    "date": "2025",
    "capability_axis_change": "none",
    "morphology_change": "aggregate 5 safety benchmarks 6 categories",
    "saturation_driver": "fragmented_eval",
    "source_url": "https://www.evidentlyai.com/blog/llm-safety-bias-benchmarks"
  },
  {
    "event_id": "E035",
    "family": "safety",
    "from_version": "HarmBench",
    "to_version": "Agent-SafetyBench",
    "date": "2025",
    "capability_axis_change": "agent_safety",
    "morphology_change": "LLM agent safety scenarios",
    "saturation_driver": "domain_expansion",
    "source_url": "https://www.evidentlyai.com/blog/llm-safety-bias-benchmarks"
  },
  {
    "event_id": "E036",
    "family": "code",
    "from_version": "HumanEval",
    "to_version": "HumanEval+",
    "date": "2023",
    "capability_axis_change": "none",
    "morphology_change": "80x more test cases + corrected solutions",
    "saturation_driver": "inadequate_test_coverage",
    "source_url": "https://arxiv.org/abs/2305.01210"
  },
  {
    "event_id": "E037",
    "family": "code",
    "from_version": "MBPP",
    "to_version": "MBPP+",
    "date": "2023",
    "capability_axis_change": "none",
    "morphology_change": "35x more test cases",
    "saturation_driver": "inadequate_test_coverage",
    "source_url": "https://arxiv.org/abs/2305.01210"
  },
  {
    "event_id": "E038",
    "family": "code",
    "from_version": "MBPP",
    "to_version": "MBPP-sanitized",
    "date": "2022",
    "capability_axis_change": "none",
    "morphology_change": "427 clarified descriptions",
    "saturation_driver": "ambiguous_descriptions",
    "source_url": "https://arxiv.org/abs/2108.07732"
  },
  {
    "event_id": "E039",
    "family": "code",
    "from_version": "HumanEval",
    "to_version": "MultiPL-E",
    "date": "2023",
    "capability_axis_change": "multilingual_code",
    "morphology_change": "extend to 18+ programming languages",
    "saturation_driver": "language_coverage_narrow",
    "source_url": "https://arxiv.org/abs/2208.08227"
  },
  {
    "event_id": "E040",
    "family": "code",
    "from_version": "HumanEval",
    "to_version": "LiveCodeBench",
    "date": "2024",
    "capability_axis_change": "none",
    "morphology_change": "contamination-free continuously evolving",
    "saturation_driver": "contamination",
    "source_url": "https://arxiv.org/abs/2403.07974"
  },
  {
    "event_id": "E041",
    "family": "code",
    "from_version": "HumanEval",
    "to_version": "BigCodeBench",
    "date": "2025",
    "capability_axis_change": "complex_library_use",
    "morphology_change": "1140 tasks 139 libraries real-world",
    "saturation_driver": "too_simple_isolated",
    "source_url": "https://arxiv.org/abs/2406.15877"
  },
  {
    "event_id": "E042",
    "family": "code",
    "from_version": "HumanEval",
    "to_version": "CoderEval",
    "date": "2023",
    "capability_axis_change": "repo_level",
    "morphology_change": "repository-level real-world functions",
    "saturation_driver": "function-level_unrealistic",
    "source_url": "https://arxiv.org/abs/2302.00288"
  },
  {
    "event_id": "E043",
    "family": "code",
    "from_version": "HumanEval",
    "to_version": "HumanEval-Pro",
    "date": "2024",
    "capability_axis_change": "self_invoking",
    "morphology_change": "self-invoking code generation",
    "saturation_driver": "difficulty_insufficient",
    "source_url": "https://arxiv.org/abs/2412.21199"
  },
  {
    "event_id": "E044",
    "family": "multilingual",
    "from_version": "XNLI",
    "to_version": "XTREME",
    "date": "2020",
    "capability_axis_change": "multi_task",
    "morphology_change": "40 languages 9 tasks",
    "saturation_driver": "single_task_narrow",
    "source_url": "https://arxiv.org/abs/2003.11080"
  },
  {
    "event_id": "E045",
    "family": "multilingual",
    "from_version": "XTREME",
    "to_version": "XTREME-R",
    "date": "2021",
    "capability_axis_change": "none",
    "morphology_change": "refined + more languages",
    "saturation_driver": "coverage_gaps",
    "source_url": "https://arxiv.org/abs/2104.07412"
  },
  {
    "event_id": "E046",
    "family": "multilingual",
    "from_version": "XTREME",
    "to_version": "MEGA",
    "date": "2023",
    "capability_axis_change": "generative_llm",
    "morphology_change": "70 languages generative-LLM eval",
    "saturation_driver": "encoder-only_outdated",
    "source_url": "https://arxiv.org/abs/2303.12528"
  },
  {
    "event_id": "E047",
    "family": "longcontext",
    "from_version": "NIAH",
    "to_version": "RULER",
    "date": "2024",
    "capability_axis_change": "multi_task_synthetic",
    "morphology_change": "13 synthetic tasks beyond retrieval",
    "saturation_driver": "retrieval-only_too_easy",
    "source_url": "https://arxiv.org/abs/2404.06654"
  },
  {
    "event_id": "E048",
    "family": "longcontext",
    "from_version": "NIAH",
    "to_version": "LongBench",
    "date": "2023",
    "capability_axis_change": "realistic_tasks",
    "morphology_change": "multi-domain realistic long docs",
    "saturation_driver": "toy_retrieval_unrealistic",
    "source_url": "https://arxiv.org/abs/2308.14508"
  },
  {
    "event_id": "E049",
    "family": "longcontext",
    "from_version": "LongBench",
    "to_version": "InfiniteBench",
    "date": "2024",
    "capability_axis_change": "longer_context",
    "morphology_change": "avg length >100K-200K tokens",
    "saturation_driver": "length_too_modest",
    "source_url": "https://arxiv.org/abs/2402.13718"
  },
  {
    "event_id": "E050",
    "family": "longcontext",
    "from_version": "RULER",
    "to_version": "NoLiMa",
    "date": "2025",
    "capability_axis_change": "latent_reasoning",
    "morphology_change": "minimal lexical overlap reasoning",
    "saturation_driver": "keyword_matching_shortcut",
    "source_url": "https://llm-stats.com/benchmarks"
  },
  {
    "event_id": "E051",
    "family": "longcontext",
    "from_version": "RULER",
    "to_version": "BABILong",
    "date": "2024",
    "capability_axis_change": "multi_hop_reasoning",
    "morphology_change": "multi-hop over long context",
    "saturation_driver": "retrieval-only_insufficient",
    "source_url": "https://arxiv.org/abs/2406.10149"
  },
  {
    "event_id": "E052",
    "family": "longcontext",
    "from_version": "LongBench",
    "to_version": "HELMET",
    "date": "2024",
    "capability_axis_change": "none",
    "morphology_change": "controllable diverse + LC-distinction",
    "saturation_driver": "uncontrolled_lengths",
    "source_url": "https://arxiv.org/abs/2410.02694"
  },
  {
    "event_id": "E053",
    "family": "rag",
    "from_version": "SQuAD",
    "to_version": "HotpotQA",
    "date": "2018",
    "capability_axis_change": "multi_hop",
    "morphology_change": "multi-hop bridging reasoning",
    "saturation_driver": "single_hop_too_easy",
    "source_url": "https://arxiv.org/abs/1809.09600"
  },
  {
    "event_id": "E054",
    "family": "rag",
    "from_version": "HotpotQA",
    "to_version": "MuSiQue",
    "date": "2022",
    "capability_axis_change": "harder_multihop",
    "morphology_change": "compositionally complex sub-questions",
    "saturation_driver": "multihop_too_easy",
    "source_url": "https://arxiv.org/abs/2108.00573"
  },
  {
    "event_id": "E055",
    "family": "rag",
    "from_version": "NaturalQuestions",
    "to_version": "BEIR",
    "date": "2021",
    "capability_axis_change": "heterogeneous",
    "morphology_change": "aggregate 18 datasets 9 task types",
    "saturation_driver": "fragmented_single-domain",
    "source_url": "https://arxiv.org/abs/2104.08663"
  },
  {
    "event_id": "E056",
    "family": "rag",
    "from_version": "BEIR",
    "to_version": "FeB4RAG",
    "date": "2024",
    "capability_axis_change": "federated",
    "morphology_change": "federated retrieval 790 conv queries",
    "saturation_driver": "no_federated_eval",
    "source_url": "https://arxiv.org/abs/2402.11891"
  },
  {
    "event_id": "E057",
    "family": "rag",
    "from_version": "NaturalQuestions",
    "to_version": "QE-RAG",
    "date": "2025",
    "capability_axis_change": "robustness",
    "morphology_change": "inject query entry errors",
    "saturation_driver": "no_robustness_eval",
    "source_url": "https://arxiv.org/abs/2504.04062"
  },
  {
    "event_id": "E058",
    "family": "rag",
    "from_version": "NaturalQuestions",
    "to_version": "MIRAGE",
    "date": "2025",
    "capability_axis_change": "medical_domain",
    "morphology_change": "medical RAG 7663 questions",
    "saturation_driver": "domain_expansion",
    "source_url": "https://arxiv.org/abs/2402.13178"
  },
  {
    "event_id": "E059",
    "family": "rag",
    "from_version": "NaturalQuestions",
    "to_version": "PopQA",
    "date": "2022",
    "capability_axis_change": "long_tail",
    "morphology_change": "long-tail entity knowledge",
    "saturation_driver": "head-entity_bias",
    "source_url": "https://arxiv.org/abs/2212.10511"
  },
  {
    "event_id": "E060",
    "family": "bfcl",
    "from_version": "BFCL-v1",
    "to_version": "BFCL-v2",
    "date": "2024-08-20",
    "capability_axis_change": "enterprise_live",
    "morphology_change": "enterprise + OSS-contributed live functions",
    "saturation_driver": "synthetic_unrealistic",
    "source_url": "https://gorilla.cs.berkeley.edu/leaderboard.html"
  },
  {
    "event_id": "E061",
    "family": "bfcl",
    "from_version": "BFCL-v2",
    "to_version": "BFCL-v3",
    "date": "2024-09-21",
    "capability_axis_change": "multi_turn",
    "morphology_change": "multi-turn multi-step state-based",
    "saturation_driver": "single_turn_insufficient",
    "source_url": "https://gorilla.cs.berkeley.edu/leaderboard.html"
  },
  {
    "event_id": "E062",
    "family": "bfcl",
    "from_version": "BFCL-v3",
    "to_version": "BFCL-v4",
    "date": "2025",
    "capability_axis_change": "agentic",
    "morphology_change": "holistic agentic evaluation",
    "saturation_driver": "function-call_insufficient",
    "source_url": "https://gorilla.cs.berkeley.edu/leaderboard.html"
  },
  {
    "event_id": "E063",
    "family": "embodied",
    "from_version": "Habitat",
    "to_version": "Habitat2.0",
    "date": "2022",
    "capability_axis_change": "interactive_rearrangement",
    "morphology_change": "nav/pick/place/open/close skills",
    "saturation_driver": "static_navigation_insufficient",
    "source_url": "https://arxiv.org/pdf/2210.06849"
  },
  {
    "event_id": "E064",
    "family": "embodied",
    "from_version": "Habitat2.0",
    "to_version": "Habitat3.0",
    "date": "2023",
    "capability_axis_change": "human_robot_collab",
    "morphology_change": "human-robot collaboration scenarios",
    "saturation_driver": "single_agent_insufficient",
    "source_url": "https://arxiv.org/pdf/2210.06849"
  },
  {
    "event_id": "E065",
    "family": "embodied",
    "from_version": "BEHAVIOR",
    "to_version": "BEHAVIOR-1K",
    "date": "2024",
    "capability_axis_change": "scale_diversity",
    "morphology_change": "1000 everyday activities realistic sim",
    "saturation_driver": "limited_activities",
    "source_url": "https://jiajunwu.com/papers/behavior1k_corl.pdf"
  },
  {
    "event_id": "E066",
    "family": "embodied",
    "from_version": "ALFRED",
    "to_version": "EmbodiedBench",
    "date": "2025",
    "capability_axis_change": "unified_multi_env",
    "morphology_change": "4 envs 1128 instances aggregate",
    "saturation_driver": "fragmented_single-env",
    "source_url": "https://arxiv.org/html/2502.09560v1"
  },
  {
    "event_id": "E067",
    "family": "embodied",
    "from_version": "Habitat",
    "to_version": "VLN-CE",
    "date": "2020",
    "capability_axis_change": "language_navigation",
    "morphology_change": "natural language instruction nav",
    "saturation_driver": "no_language_grounding",
    "source_url": "https://arxiv.org/pdf/2210.06849"
  },
  {
    "event_id": "E068",
    "family": "medical",
    "from_version": "PubMedQA",
    "to_version": "MedQA",
    "date": "2021",
    "capability_axis_change": "exam_knowledge",
    "morphology_change": "USMLE multilingual board exams",
    "saturation_driver": "literature-only_narrow",
    "source_url": "https://www.emergentmind.com/topics/medqa-and-medmcqa"
  },
  {
    "event_id": "E069",
    "family": "medical",
    "from_version": "MedQA",
    "to_version": "MedMCQA",
    "date": "2022",
    "capability_axis_change": "scale_breadth",
    "morphology_change": "194k MCQ diverse healthcare",
    "saturation_driver": "limited_scale",
    "source_url": "https://www.emergentmind.com/topics/medqa-and-medmcqa"
  },
  {
    "event_id": "E070",
    "family": "medical",
    "from_version": "MedQA",
    "to_version": "MultiMedQA",
    "date": "2023",
    "capability_axis_change": "composite",
    "morphology_change": "aggregate 7 medical QA datasets",
    "saturation_driver": "fragmented_single-dataset",
    "source_url": "https://arxiv.org/pdf/2303.13375"
  },
  {
    "event_id": "E071",
    "family": "medical",
    "from_version": "MultiMedQA",
    "to_version": "MedXpertQA",
    "date": "2025",
    "capability_axis_change": "expert_multimodal",
    "morphology_change": "4460 expert-level 2005 multimodal",
    "saturation_driver": "difficulty_insufficient",
    "source_url": "https://arxiv.org/pdf/2501.18362"
  },
  {
    "event_id": "E072",
    "family": "medical",
    "from_version": "MedQA",
    "to_version": "HealthBench",
    "date": "2025",
    "capability_axis_change": "multi_turn_rubric",
    "morphology_change": "multi-turn rubric expert-validated",
    "saturation_driver": "static_knowledge_insufficient",
    "source_url": "https://arxiv.org/html/2604.27470v1"
  },
  {
    "event_id": "E073",
    "family": "medical",
    "from_version": "HealthBench",
    "to_version": "HealthBench-Professional",
    "date": "2026",
    "capability_axis_change": "real_clinician",
    "morphology_change": "real clinician chats",
    "saturation_driver": "synthetic_unrealistic",
    "source_url": "https://arxiv.org/html/2604.27470v1"
  },
  {
    "event_id": "E074",
    "family": "instruction",
    "from_version": "MT-Bench",
    "to_version": "IFEval",
    "date": "2023",
    "capability_axis_change": "objective_verifiable",
    "morphology_change": "verifiable instructions no LLM-judge",
    "saturation_driver": "llm-judge_subjective_bias",
    "source_url": "https://aclanthology.org/2025.findings-naacl.344.pdf"
  },
  {
    "event_id": "E075",
    "family": "instruction",
    "from_version": "AlpacaEval",
    "to_version": "AlpacaEval2.0",
    "date": "2024",
    "capability_axis_change": "none",
    "morphology_change": "GPT-4-Turbo judge + length-controlled win rate",
    "saturation_driver": "length_bias_outdated_baseline",
    "source_url": "https://arxiv.org/pdf/2406.11939"
  },
  {
    "event_id": "E076",
    "family": "instruction",
    "from_version": "MT-Bench",
    "to_version": "Arena-Hard",
    "date": "2024",
    "capability_axis_change": "harder_queries",
    "morphology_change": "500 hard queries high separability",
    "saturation_driver": "low_separability",
    "source_url": "https://arxiv.org/pdf/2406.11939"
  },
  {
    "event_id": "E077",
    "family": "instruction",
    "from_version": "IFEval",
    "to_version": "M-IFEval",
    "date": "2025",
    "capability_axis_change": "multilingual",
    "morphology_change": "multilingual instruction following",
    "saturation_driver": "english-only_narrow",
    "source_url": "https://arxiv.org/pdf/2502.04688"
  },
  {
    "event_id": "E078",
    "family": "instruction",
    "from_version": "MT-Bench",
    "to_version": "MT-Bench-101",
    "date": "2024",
    "capability_axis_change": "fine_grained",
    "morphology_change": "fine-grained multi-turn hierarchy",
    "saturation_driver": "coarse_eval",
    "source_url": "https://aclanthology.org/2024.acl-long.401.pdf"
  },
  {
    "event_id": "E079",
    "family": "commonsense",
    "from_version": "WinogradSchema",
    "to_version": "WinoGrande",
    "date": "2021",
    "capability_axis_change": "scale_adversarial",
    "morphology_change": "large-scale + adversarial filtering",
    "saturation_driver": "statistical_shortcut",
    "source_url": "https://arxiv.org/abs/1907.10641"
  },
  {
    "event_id": "E080",
    "family": "commonsense",
    "from_version": "SWAG",
    "to_version": "HellaSwag",
    "date": "2019",
    "capability_axis_change": "adversarial_harder",
    "morphology_change": "adversarial filtering harder endings",
    "saturation_driver": "too_easy_word_assoc",
    "source_url": "https://mbrenndoerfer.com/writing/hellaswag-adversarial-filtering-commonsense-benchmark"
  },
  {
    "event_id": "E081",
    "family": "commonsense",
    "from_version": "ARC-AGI",
    "to_version": "ARC-AGI-2",
    "date": "2025",
    "capability_axis_change": "harder_transforms",
    "morphology_change": "more complex transformations",
    "saturation_driver": "saturation",
    "source_url": "https://github.com/BenchGecko/awesome-llm-benchmarks"
  },
  {
    "event_id": "E082",
    "family": "agent",
    "from_version": "WebShop",
    "to_version": "Mind2Web",
    "date": "2023",
    "capability_axis_change": "realistic_web",
    "morphology_change": "2350 real-website tasks",
    "saturation_driver": "synthetic_unrealistic",
    "source_url": "https://osu-nlp-group.github.io/Mind2Web/"
  },
  {
    "event_id": "E083",
    "family": "agent",
    "from_version": "Mind2Web",
    "to_version": "Online-Mind2Web",
    "date": "2024",
    "capability_axis_change": "live_web",
    "morphology_change": "live-web evaluation variant",
    "saturation_driver": "offline_contamination",
    "source_url": "https://leaderboard.steel.dev/"
  },
  {
    "event_id": "E084",
    "family": "agent",
    "from_version": "Mind2Web",
    "to_version": "MT-Mind2Web",
    "date": "2024",
    "capability_axis_change": "multi_turn",
    "morphology_change": "multi-turn conversational nav",
    "saturation_driver": "single_turn_insufficient",
    "source_url": "https://github.com/OSU-NLP-Group/GUI-Agents-Paper-List/blob/main/paper_by_key/paper_benchmark.md"
  },
  {
    "event_id": "E085",
    "family": "agent",
    "from_version": "WebShop",
    "to_version": "AgentBench",
    "date": "2023",
    "capability_axis_change": "multi_environment",
    "morphology_change": "8 interactive environments aggregate",
    "saturation_driver": "single-env_narrow",
    "source_url": "https://leaderboard.steel.dev/"
  },
  {
    "event_id": "E086",
    "family": "agent",
    "from_version": "OSWorld",
    "to_version": "OSWorld-Verified",
    "date": "2024",
    "capability_axis_change": "none",
    "morphology_change": "programmatically-verifiable subset",
    "saturation_driver": "verification_unreliable",
    "source_url": "https://www.emergentmind.com/topics/osworld-verified-and-androidworld-benchmarks"
  },
  {
    "event_id": "E087",
    "family": "agent",
    "from_version": "OSWorld",
    "to_version": "AndroidWorld",
    "date": "2024",
    "capability_axis_change": "mobile_domain",
    "morphology_change": "dynamic mobile parameterized tasks",
    "saturation_driver": "desktop-only_narrow",
    "source_url": "https://www.emergentmind.com/topics/osworld-verified-and-androidworld-benchmarks"
  },
  {
    "event_id": "E088",
    "family": "audio",
    "from_version": "SUPERB",
    "to_version": "Dynamic-SUPERB",
    "date": "2023",
    "capability_axis_change": "instruction_following",
    "morphology_change": "instruction-following speech eval",
    "saturation_driver": "static_encoder_insufficient",
    "source_url": "https://arxiv.org/pdf/2506.10019"
  },
  {
    "event_id": "E089",
    "family": "audio",
    "from_version": "Dynamic-SUPERB",
    "to_version": "Dynamic-SUPERB-Phase2",
    "date": "2025",
    "capability_axis_change": "scale_modality",
    "morphology_change": "180 tasks speech/music/sound",
    "saturation_driver": "limited_scope",
    "source_url": "https://arxiv.org/html/2508.13992v1"
  },
  {
    "event_id": "E090",
    "family": "audio",
    "from_version": "SUPERB",
    "to_version": "AIR-Bench",
    "date": "2024",
    "capability_axis_change": "audio_chat",
    "morphology_change": "speech/sound/music + chat",
    "saturation_driver": "no_chat_generation",
    "source_url": "https://arxiv.org/html/2402.07729v2"
  },
  {
    "event_id": "E091",
    "family": "audio",
    "from_version": "MMAU",
    "to_version": "MMAU-Pro",
    "date": "2025",
    "capability_axis_change": "holistic_harder",
    "morphology_change": "holistic audio intelligence harder",
    "saturation_driver": "saturation",
    "source_url": "https://arxiv.org/html/2508.13992v1"
  },
  {
    "event_id": "E092",
    "family": "science",
    "from_version": "MMLU",
    "to_version": "ScienceQA",
    "date": "2022",
    "capability_axis_change": "multimodal_science",
    "morphology_change": "21k multimodal science QA",
    "saturation_driver": "text-only_narrow",
    "source_url": "https://www.researchgate.net/publication/379293150_SciEval"
  },
  {
    "event_id": "E093",
    "family": "science",
    "from_version": "ScienceQA",
    "to_version": "SciBench",
    "date": "2023",
    "capability_axis_change": "college_level",
    "morphology_change": "692 college physics/chem/math",
    "saturation_driver": "elementary_too_easy",
    "source_url": "https://www.researchgate.net/publication/379293150_SciEval"
  },
  {
    "event_id": "E094",
    "family": "science",
    "from_version": "GPQA",
    "to_version": "SuperGPQA",
    "date": "2025",
    "capability_axis_change": "scale",
    "morphology_change": "26529 expert-level scaled",
    "saturation_driver": "limited_scale",
    "source_url": "https://arxiv.org/html/2512.22899"
  },
  {
    "event_id": "E095",
    "family": "science",
    "from_version": "SciBench",
    "to_version": "SciKnowEval",
    "date": "2024",
    "capability_axis_change": "scale_multilevel",
    "morphology_change": "28392 multi-level science",
    "saturation_driver": "limited_scale",
    "source_url": "https://arxiv.org/html/2406.09098v3"
  },
  {
    "event_id": "E096",
    "family": "timeseries",
    "from_version": "Monash",
    "to_version": "TSLib",
    "date": "2023",
    "capability_axis_change": "multi_task",
    "morphology_change": "5 tasks deep models codebase",
    "saturation_driver": "forecasting-only_narrow",
    "source_url": "https://github.com/thuml/Time-Series-Library"
  },
  {
    "event_id": "E097",
    "family": "timeseries",
    "from_version": "TSLib",
    "to_version": "TFB",
    "date": "2024",
    "capability_axis_change": "fair_traditional",
    "morphology_change": "fair benchmarking traditional+deep",
    "saturation_driver": "stereotype_bias_unfair",
    "source_url": "https://www.vldb.org/pvldb/vol17/p2363-hu.pdf"
  },
  {
    "event_id": "E098",
    "family": "timeseries",
    "from_version": "TFB",
    "to_version": "GIFT-Eval",
    "date": "2024",
    "capability_axis_change": "foundation_model",
    "morphology_change": "zero-shot FM eval + non-leak pretrain",
    "saturation_driver": "no_FM_eval",
    "source_url": "https://arxiv.org/abs/2410.10393"
  },
  {
    "event_id": "E099",
    "family": "timeseries",
    "from_version": "Monash",
    "to_version": "Monash-v2",
    "date": "2023",
    "capability_axis_change": "scale",
    "morphology_change": "20->30 datasets 400k series",
    "saturation_driver": "limited_datasets",
    "source_url": "https://arxiv.org/abs/2105.06643"
  },
  {
    "event_id": "E100",
    "family": "timeseries",
    "from_version": "GIFT-Eval",
    "to_version": "GIFT-Eval-v2",
    "date": "2024-11-11",
    "capability_axis_change": "none",
    "morphology_change": "refined splits",
    "saturation_driver": "split_issues",
    "source_url": "https://arxiv.org/abs/2410.10393"
  },
  {
    "event_id": "E101",
    "family": "game",
    "from_version": "TextWorld",
    "to_version": "ALFWorld",
    "date": "2021",
    "capability_axis_change": "embodied_household",
    "morphology_change": "embodied ALFRED in text 6 task types",
    "saturation_driver": "abstract_text-only",
    "source_url": "https://github.com/nec-research/agentquest/blob/main/agentquest/benchmarks/alfworld/README.md"
  },
  {
    "event_id": "E102",
    "family": "game",
    "from_version": "Crafter",
    "to_version": "Craftax",
    "date": "2024",
    "capability_axis_change": "harder_complex",
    "morphology_change": "JAX-accelerated more complex",
    "saturation_driver": "limited_complexity",
    "source_url": "https://arxiv.org/html/2310.01557v5"
  },
  {
    "event_id": "E103",
    "family": "game",
    "from_version": "Crafter",
    "to_version": "SmartPlay",
    "date": "2023",
    "capability_axis_change": "multi_game",
    "morphology_change": "aggregate bandits/RPS/Crafter/Minecraft",
    "saturation_driver": "single-game_narrow",
    "source_url": "https://arxiv.org/pdf/2310.01557"
  },
  {
    "event_id": "E104",
    "family": "game",
    "from_version": "NetHack",
    "to_version": "BALROG",
    "date": "2024",
    "capability_axis_change": "unified_agentic",
    "morphology_change": "aggregate TextWorld/Crafter/NetHack",
    "saturation_driver": "fragmented_single-game",
    "source_url": "https://arxiv.org/pdf/2411.13543"
  },
  {
    "event_id": "E105",
    "family": "video",
    "from_version": "MVBench",
    "to_version": "Video-MME",
    "date": "2024",
    "capability_axis_change": "longer_multimodal",
    "morphology_change": "900 videos up to 1hr audio+visual",
    "saturation_driver": "short-clip_narrow",
    "source_url": "https://llm-stats.com/benchmarks"
  },
  {
    "event_id": "E106",
    "family": "video",
    "from_version": "EgoSchema",
    "to_version": "X-LeBench",
    "date": "2025",
    "capability_axis_change": "ultra_long_ego",
    "morphology_change": "142-516min egocentric",
    "saturation_driver": "3min_too_short",
    "source_url": "https://arxiv.org/pdf/2501.06835"
  },
  {
    "event_id": "E107",
    "family": "video",
    "from_version": "Video-MME",
    "to_version": "MLVU",
    "date": "2024",
    "capability_axis_change": "longer_multitask",
    "morphology_change": "3min-2hr 9 tasks",
    "saturation_driver": "duration_limited",
    "source_url": "https://arxiv.org/pdf/2506.02850"
  },
  {
    "event_id": "E108",
    "family": "video",
    "from_version": "Video-MME",
    "to_version": "LVBench",
    "date": "2024",
    "capability_axis_change": "extreme_long",
    "morphology_change": "68min avg long-term memory",
    "saturation_driver": "duration_limited",
    "source_url": "https://arxiv.org/pdf/2506.02850"
  },
  {
    "event_id": "E109",
    "family": "video",
    "from_version": "MVBench",
    "to_version": "CrossVid",
    "date": "2025",
    "capability_axis_change": "cross_video",
    "morphology_change": "reason over multiple videos",
    "saturation_driver": "single-video_narrow",
    "source_url": "https://arxiv.org/pdf/2506.02850"
  },
  {
    "event_id": "E110",
    "family": "glue",
    "from_version": "GLUE",
    "to_version": "SuperGLUE",
    "date": "2019",
    "capability_axis_change": "harder_reasoning",
    "morphology_change": "longer-text reasoning tasks",
    "saturation_driver": "saturation_human-level",
    "source_url": "https://arxiv.org/pdf/1905.00537"
  },
  {
    "event_id": "E111",
    "family": "glue",
    "from_version": "BIG-bench",
    "to_version": "BIG-bench-Hard",
    "date": "2022",
    "capability_axis_change": "harder_subset",
    "morphology_change": "hard subset of BIG-bench",
    "saturation_driver": "too_easy_subset",
    "source_url": "https://arxiv.org/html/2502.19187v1"
  },
  {
    "event_id": "E112",
    "family": "glue",
    "from_version": "BIG-bench-Hard",
    "to_version": "BIG-bench-Extra-Hard",
    "date": "2025",
    "capability_axis_change": "harder_frontier",
    "morphology_change": "amplified difficulty preserve diversity",
    "saturation_driver": "saturation_ceiling",
    "source_url": "https://arxiv.org/html/2502.19187v1"
  },
  {
    "event_id": "E113",
    "family": "glue",
    "from_version": "GLUE",
    "to_version": "AdversarialNLI",
    "date": "2020",
    "capability_axis_change": "adversarial",
    "morphology_change": "human-and-model-in-loop adversarial",
    "saturation_driver": "saturation",
    "source_url": "https://medium.com/@myschang/benchmark-of-llms-part-1-glue-superglue-adversarial-nli-big-bench-8d1aed6bae12"
  },
  {
    "event_id": "E114",
    "family": "t2i",
    "from_version": "COCO",
    "to_version": "DrawBench",
    "date": "2022",
    "capability_axis_change": "compositional",
    "morphology_change": "200 prompts counting/composition",
    "saturation_driver": "limited_diversity",
    "source_url": "https://proceedings.neurips.cc/paper_files/paper/2023/file/f8ad010cdd9143dbb0e9308c093aff24-Paper-Datasets_and_Benchmarks.pdf"
  },
  {
    "event_id": "E115",
    "family": "t2i",
    "from_version": "DrawBench",
    "to_version": "GenEval",
    "date": "2023",
    "capability_axis_change": "object_focused",
    "morphology_change": "object detection co-occur/count/color",
    "saturation_driver": "subjective_eval",
    "source_url": "https://github.com/Karine-Huang/T2I-CompBench"
  },
  {
    "event_id": "E116",
    "family": "t2i",
    "from_version": "GenEval",
    "to_version": "T2I-CompBench",
    "date": "2023",
    "capability_axis_change": "comprehensive_compositional",
    "morphology_change": "6000 prompts 3 categories",
    "saturation_driver": "narrow_compositional",
    "source_url": "https://arxiv.org/abs/2307.06350"
  },
  {
    "event_id": "E117",
    "family": "t2i",
    "from_version": "T2I-CompBench",
    "to_version": "T2I-CompBench++",
    "date": "2024",
    "capability_axis_change": "enhanced",
    "morphology_change": "8000 prompts +3D-spatial+numeracy+MLLM metrics",
    "saturation_driver": "limited_categories",
    "source_url": "https://arxiv.org/abs/2307.06350"
  },
  {
    "event_id": "E118",
    "family": "ocr",
    "from_version": "OCRBench",
    "to_version": "OCRBench-v2",
    "date": "2025",
    "capability_axis_change": "localization_reasoning",
    "morphology_change": "EN/ZH tracks broader tasks",
    "saturation_driver": "narrow_text-recog",
    "source_url": "https://arxiv.org/html/2501.00321v2"
  },
  {
    "event_id": "E119",
    "family": "ocr",
    "from_version": "ChartQA",
    "to_version": "ChartQAPro",
    "date": "2025",
    "capability_axis_change": "harder_charts",
    "morphology_change": "significantly harder chart reasoning",
    "saturation_driver": "saturation",
    "source_url": "https://arxiv.org/html/2603.13398v1"
  },
  {
    "event_id": "E120",
    "family": "ocr",
    "from_version": "DocVQA",
    "to_version": "MP-DocVQA",
    "date": "2024",
    "capability_axis_change": "multi_page",
    "morphology_change": "multi-page long documents",
    "saturation_driver": "single-page_narrow",
    "source_url": "https://arxiv.org/pdf/2502.13923"
  },
  {
    "event_id": "E121",
    "family": "ocr",
    "from_version": "OmniDocBench",
    "to_version": "OmniDocBench-v1.5",
    "date": "2025",
    "capability_axis_change": "none",
    "morphology_change": "refined document parsing",
    "saturation_driver": "parsing_quality",
    "source_url": "https://arxiv.org/pdf/2502.13923"
  },
  {
    "event_id": "E122",
    "family": "table",
    "from_version": "WikiSQL",
    "to_version": "Spider",
    "date": "2018",
    "capability_axis_change": "complex_sql",
    "morphology_change": "10181 questions multi-table 138 domains",
    "saturation_driver": "simple_sql_narrow",
    "source_url": "https://arxiv.org/pdf/2305.09645"
  },
  {
    "event_id": "E123",
    "family": "table",
    "from_version": "Spider",
    "to_version": "BIRD",
    "date": "2023",
    "capability_axis_change": "external_knowledge",
    "morphology_change": "12751 pairs +external knowledge complex",
    "saturation_driver": "too_easy_clean",
    "source_url": "https://arxiv.org/pdf/2410.04739"
  },
  {
    "event_id": "E124",
    "family": "table",
    "from_version": "Spider",
    "to_version": "Spider-SYN",
    "date": "2021",
    "capability_axis_change": "adversarial_synonym",
    "morphology_change": "synonym substitution harder",
    "saturation_driver": "column-name_shortcut",
    "source_url": "https://arxiv.org/pdf/2305.18961"
  },
  {
    "event_id": "E125",
    "family": "table",
    "from_version": "WikiTableQuestions",
    "to_version": "TabFact",
    "date": "2019",
    "capability_axis_change": "fact_verification",
    "morphology_change": "table-based fact verification",
    "saturation_driver": "qa-only_narrow",
    "source_url": "https://www.researchgate.net/publication/335651216_TabFact"
  },
  {
    "event_id": "E126",
    "family": "table",
    "from_version": "Spider",
    "to_version": "MMTU",
    "date": "2025",
    "capability_axis_change": "massive_multitask",
    "morphology_change": "unify many table tasks multi-table",
    "saturation_driver": "narrow_sql-qa",
    "source_url": "https://arxiv.org/html/2506.05587v3"
  },
  {
    "event_id": "E127",
    "family": "hallucination",
    "from_version": "TruthfulQA",
    "to_version": "HaluEval",
    "date": "2023",
    "capability_axis_change": "detection_scale",
    "morphology_change": "10k-35k annotated hallucination detection",
    "saturation_driver": "misconception-only_narrow",
    "source_url": "https://www.emergentmind.com/topics/halueval-and-truthfulqa"
  },
  {
    "event_id": "E128",
    "family": "hallucination",
    "from_version": "HaluEval",
    "to_version": "HaluEval2.0",
    "date": "2024",
    "capability_axis_change": "diverse_tasks",
    "morphology_change": "open-ended QA diverse tasks",
    "saturation_driver": "limited_scope",
    "source_url": "https://arxiv.org/html/2504.17550v1"
  },
  {
    "event_id": "E129",
    "family": "hallucination",
    "from_version": "TruthfulQA",
    "to_version": "SimpleQA",
    "date": "2024",
    "capability_axis_change": "contamination_free",
    "morphology_change": "4326 withheld fact-seeking questions",
    "saturation_driver": "contamination_saturation",
    "source_url": "https://www.emergentmind.com/topics/halueval-and-truthfulqa"
  },
  {
    "event_id": "E130",
    "family": "hallucination",
    "from_version": "HaluEval",
    "to_version": "HalluLens",
    "date": "2025",
    "capability_axis_change": "multi_task_unified",
    "morphology_change": "broad multi-task + distinguish factuality",
    "saturation_driver": "fragmented_intertwined",
    "source_url": "https://arxiv.org/html/2504.17550v1"
  },
  {
    "event_id": "E131",
    "family": "hallucination",
    "from_version": "TruthfulQA",
    "to_version": "FreshQA",
    "date": "2023",
    "capability_axis_change": "time_sensitive",
    "morphology_change": "time-sensitive factual questions",
    "saturation_driver": "static_outdated",
    "source_url": "https://arxiv.org/html/2504.17550v1"
  },
  {
    "event_id": "E132",
    "family": "threed",
    "from_version": "ScanQA",
    "to_version": "SQA3D",
    "date": "2022",
    "capability_axis_change": "situated_embodied",
    "morphology_change": "33.4k situated agent-position QA",
    "saturation_driver": "scene-only_narrow",
    "source_url": "https://jeasinema.github.io/file/sqa3d_iclr23.pdf"
  },
  {
    "event_id": "E133",
    "family": "threed",
    "from_version": "ScanQA",
    "to_version": "3DMV-VQA",
    "date": "2023",
    "capability_axis_change": "multi_view",
    "morphology_change": "50k multi-view reasoning",
    "saturation_driver": "single-view_narrow",
    "source_url": "https://arxiv.org/pdf/2502.00342"
  },
  {
    "event_id": "E134",
    "family": "threed",
    "from_version": "ScanQA",
    "to_version": "MV-ScanQA",
    "date": "2025",
    "capability_axis_change": "multi_view_successor",
    "morphology_change": "multi-view reasoning challenge",
    "saturation_driver": "single-view_limited",
    "source_url": "https://dl.acm.org/doi/10.1145/3746027.3758244"
  },
  {
    "event_id": "E135",
    "family": "threed",
    "from_version": "ScanQA",
    "to_version": "CLEVR3D",
    "date": "2022",
    "capability_axis_change": "template_scaleup",
    "morphology_change": "4x questions broader attributes",
    "saturation_driver": "limited_questions",
    "source_url": "https://arxiv.org/pdf/2502.00342"
  },
  {
    "event_id": "E136",
    "family": "swecoding",
    "from_version": "SWE-bench",
    "to_version": "SWE-bench-Pro",
    "date": "2025",
    "capability_axis_change": "long_horizon",
    "morphology_change": "harder long-horizon ~23pct top",
    "saturation_driver": "saturation_70pct",
    "source_url": "https://arxiv.org/html/2509.16941v1"
  },
  {
    "event_id": "E137",
    "family": "swecoding",
    "from_version": "SWE-bench",
    "to_version": "SWE-rebench",
    "date": "2025",
    "capability_axis_change": "decontaminated_dynamic",
    "morphology_change": "continuously-evolving decontaminated",
    "saturation_driver": "contamination_static",
    "source_url": "https://arxiv.org/pdf/2505.20411"
  },
  {
    "event_id": "E138",
    "family": "swecoding",
    "from_version": "SWE-rebench",
    "to_version": "SWE-rebench-V2",
    "date": "2026",
    "capability_axis_change": "language_agnostic",
    "morphology_change": "multi-language SWE tasks",
    "saturation_driver": "python-only_narrow",
    "source_url": "https://arxiv.org/pdf/2602.23866"
  },
  {
    "event_id": "E139",
    "family": "swecoding",
    "from_version": "SWE-bench",
    "to_version": "Multi-SWE-bench",
    "date": "2025",
    "capability_axis_change": "multilingual",
    "morphology_change": "7 languages 1632 instances",
    "saturation_driver": "python-only_narrow",
    "source_url": "https://arxiv.org/html/2509.16941v1"
  },
  {
    "event_id": "E140",
    "family": "swecoding",
    "from_version": "RepoBench",
    "to_version": "RepoBench-v1.1",
    "date": "2024",
    "capability_axis_change": "decontaminated",
    "morphology_change": "fresh GitHub +dedup vs Stack-v2",
    "saturation_driver": "contamination",
    "source_url": "https://github.com/YerbaPage/Awesome-Repo-Level-Code-Generation"
  },
  {
    "event_id": "E141",
    "family": "reward",
    "from_version": "RewardBench",
    "to_version": "RM-Bench",
    "date": "2024",
    "capability_axis_change": "subtle_style_robust",
    "morphology_change": "sensitivity to subtle content + style bias",
    "saturation_driver": "style_bias_low_correlation",
    "source_url": "https://arxiv.org/abs/2410.16184"
  },
  {
    "event_id": "E142",
    "family": "reward",
    "from_version": "RewardBench",
    "to_version": "RewardBench2",
    "date": "2025",
    "capability_axis_change": "harder_realistic",
    "morphology_change": "1-vs-3 format fresh prompts 6 domains",
    "saturation_driver": "saturation_easy",
    "source_url": "https://arxiv.org/pdf/2506.01937"
  },
  {
    "event_id": "E143",
    "family": "reward",
    "from_version": "RewardBench",
    "to_version": "RMB",
    "date": "2025",
    "capability_axis_change": "comprehensive",
    "morphology_change": "broader helpfulness+harmlessness",
    "saturation_driver": "narrow_coverage",
    "source_url": "https://arxiv.org/pdf/2505.02387"
  },
  {
    "event_id": "E144",
    "family": "bias",
    "from_version": "WinoBias",
    "to_version": "StereoSet",
    "date": "2021",
    "capability_axis_change": "broad_domains",
    "morphology_change": "17995 examples gender/race/religion/profession",
    "saturation_driver": "coreference-only_narrow",
    "source_url": "https://github.com/i-gallegos/Fair-LLM-Benchmark"
  },
  {
    "event_id": "E145",
    "family": "bias",
    "from_version": "StereoSet",
    "to_version": "BBQ",
    "date": "2022",
    "capability_axis_change": "qa_format",
    "morphology_change": "50k QA 11 stereotype categories",
    "saturation_driver": "fill-blank_narrow",
    "source_url": "https://github.com/i-gallegos/Fair-LLM-Benchmark"
  },
  {
    "event_id": "E146",
    "family": "bias",
    "from_version": "CrowS-Pairs",
    "to_version": "CrowS-Pairs-revised",
    "date": "2021",
    "capability_axis_change": "none",
    "morphology_change": "corrected methodological flaws",
    "saturation_driver": "methodology_flaws",
    "source_url": "https://github.com/i-gallegos/Fair-LLM-Benchmark"
  },
  {
    "event_id": "E147",
    "family": "bias",
    "from_version": "WinoBias",
    "to_version": "WinoBias+",
    "date": "2023",
    "capability_axis_change": "neutral_rewrite",
    "morphology_change": "gender-neutral rewriting variant",
    "saturation_driver": "binary-gender_narrow",
    "source_url": "https://github.com/i-gallegos/Fair-LLM-Benchmark"
  },
  {
    "event_id": "E148",
    "family": "bias",
    "from_version": "BBQ",
    "to_version": "PBBQ",
    "date": "2025",
    "capability_axis_change": "multilingual",
    "morphology_change": "Persian bias benchmark",
    "saturation_driver": "english-only_narrow",
    "source_url": "https://arxiv.org/pdf/2510.19616"
  },
  {
    "event_id": "E149",
    "family": "mmreason",
    "from_version": "MMMU",
    "to_version": "MMMU-Pro",
    "date": "2024",
    "capability_axis_change": "harder_professional",
    "morphology_change": "upgraded harder vision+text integration",
    "saturation_driver": "saturation",
    "source_url": "https://arxiv.org/pdf/2508.11737"
  },
  {
    "event_id": "E150",
    "family": "mmreason",
    "from_version": "MathVista",
    "to_version": "MathVision",
    "date": "2024",
    "capability_axis_change": "competition_visual",
    "morphology_change": "3040 competition problems 16 disciplines",
    "saturation_driver": "consolidated_too_easy",
    "source_url": "https://www.researchgate.net/publication/397198082_Measuring_Multimodal_Mathematical_Reasoning_with_MATH-Vision_Dataset"
  },
  {
    "event_id": "E151",
    "family": "mmreason",
    "from_version": "MathVista",
    "to_version": "We-Math",
    "date": "2024",
    "capability_axis_change": "hierarchical_principle",
    "morphology_change": "67 hierarchical concepts beyond e2e",
    "saturation_driver": "end-to-end_opaque",
    "source_url": "https://arxiv.org/pdf/2509.05542"
  },
  {
    "event_id": "E152",
    "family": "mmreason",
    "from_version": "MathVista",
    "to_version": "MathVerse",
    "date": "2024",
    "capability_axis_change": "diagram_understanding",
    "morphology_change": "test true diagram understanding",
    "saturation_driver": "text-shortcut",
    "source_url": "https://arxiv.org/pdf/2506.07218"
  },
  {
    "event_id": "E153",
    "family": "mmreason",
    "from_version": "MathVista",
    "to_version": "DynaMath",
    "date": "2025",
    "capability_axis_change": "dynamic_robustness",
    "morphology_change": "dynamic problem variants robustness",
    "saturation_driver": "static_memorization",
    "source_url": "https://arxiv.org/pdf/2508.11737"
  },
  {
    "event_id": "E154",
    "family": "planning",
    "from_version": "PlanBench",
    "to_version": "PlanBench-PDDL",
    "date": "2025",
    "capability_axis_change": "formal_grounding",
    "morphology_change": "parallel PDDL encoding disambiguation",
    "saturation_driver": "underspecification",
    "source_url": "https://arxiv.org/pdf/2505.02322"
  },
  {
    "event_id": "E155",
    "family": "planning",
    "from_version": "TravelPlanner",
    "to_version": "ChinaTravel",
    "date": "2024",
    "capability_axis_change": "checkable_constraints",
    "morphology_change": "DSL explicit checkable constraints",
    "saturation_driver": "unverifiable_constraints",
    "source_url": "https://arxiv.org/pdf/2512.22673"
  },
  {
    "event_id": "E156",
    "family": "planning",
    "from_version": "TravelPlanner",
    "to_version": "TravelBench",
    "date": "2025",
    "capability_axis_change": "realistic_multiturn",
    "morphology_change": "multi-turn tool-using real queries",
    "saturation_driver": "single-task_narrow",
    "source_url": "https://arxiv.org/pdf/2512.22673"
  },
  {
    "event_id": "E157",
    "family": "planning",
    "from_version": "Blocksworld",
    "to_version": "HeroBench",
    "date": "2025",
    "capability_axis_change": "long_horizon",
    "morphology_change": "long-horizon hierarchical constraints",
    "saturation_driver": "too_simple_algorithmic",
    "source_url": "https://arxiv.org/html/2508.12782"
  },
  {
    "event_id": "E158",
    "family": "planning",
    "from_version": "PlanBench",
    "to_version": "NATURAL-PLAN",
    "date": "2024",
    "capability_axis_change": "natural_language",
    "morphology_change": "realistic NL planning trip/meeting/calendar",
    "saturation_driver": "synthetic_blocksworld",
    "source_url": "https://arxiv.org/pdf/2410.12409"
  },
  {
    "event_id": "E159",
    "family": "dialogue",
    "from_version": "MultiWOZ",
    "to_version": "MultiWOZ-2.1",
    "date": "2020",
    "capability_axis_change": "none",
    "morphology_change": "state corrections + baselines",
    "saturation_driver": "annotation_errors",
    "source_url": "https://arxiv.org/pdf/2109.14144"
  },
  {
    "event_id": "E160",
    "family": "dialogue",
    "from_version": "MultiWOZ-2.1",
    "to_version": "MultiWOZ-2.2",
    "date": "2020",
    "capability_axis_change": "none",
    "morphology_change": "additional annotation corrections",
    "saturation_driver": "annotation_errors",
    "source_url": "https://arxiv.org/pdf/2109.14144"
  },
  {
    "event_id": "E161",
    "family": "dialogue",
    "from_version": "MultiWOZ-2.1",
    "to_version": "MultiWOZ-2.4",
    "date": "2021",
    "capability_axis_change": "none",
    "morphology_change": "cleaner val/test refined",
    "saturation_driver": "annotation_errors",
    "source_url": "https://arxiv.org/pdf/2205.10059"
  },
  {
    "event_id": "E162",
    "family": "dialogue",
    "from_version": "DSTC",
    "to_version": "DSTC8-SGD",
    "date": "2020",
    "capability_axis_change": "schema_guided",
    "morphology_change": "schema-guided generalization",
    "saturation_driver": "fixed-schema_narrow",
    "source_url": "https://github.com/yukyunglee/Awesome-Dialogue-State-Tracking"
  },
  {
    "event_id": "E163",
    "family": "dialogue",
    "from_version": "MultiWOZ",
    "to_version": "DSTC11-spoken",
    "date": "2023",
    "capability_axis_change": "spoken",
    "morphology_change": "spoken version of MultiWOZ",
    "saturation_driver": "text-only_narrow",
    "source_url": "https://github.com/yukyunglee/Awesome-Dialogue-State-Tracking"
  },
  {
    "event_id": "E164",
    "family": "dialogue",
    "from_version": "PersonaChat",
    "to_version": "ConvAI2",
    "date": "2018",
    "capability_axis_change": "competition",
    "morphology_change": "persona consistency competition",
    "saturation_driver": "no_standardized_eval",
    "source_url": "http://nlpprogress.com/english/dialogue.html"
  },
  {
    "event_id": "E165",
    "family": "summ",
    "from_version": "CNN-DailyMail",
    "to_version": "XSum",
    "date": "2018",
    "capability_axis_change": "abstractive",
    "morphology_change": "single-sentence highly abstractive",
    "saturation_driver": "extractive_low-abstraction",
    "source_url": "https://arxiv.org/pdf/1907.08722"
  },
  {
    "event_id": "E166",
    "family": "summ",
    "from_version": "CNN-DailyMail",
    "to_version": "CNN-DM-v3.0.0",
    "date": "2017",
    "capability_axis_change": "none",
    "morphology_change": "non-anonymized summarization structure",
    "saturation_driver": "anonymized_qa-format",
    "source_url": "https://huggingface.co/datasets/abisee/cnn_dailymail"
  },
  {
    "event_id": "E167",
    "family": "summ",
    "from_version": "CNN-DailyMail",
    "to_version": "SummEval",
    "date": "2021",
    "capability_axis_change": "meta_eval",
    "morphology_change": "10 crowdsourced refs meta-evaluation",
    "saturation_driver": "single-ref_unreliable",
    "source_url": "https://arxiv.org/pdf/2210.17378"
  },
  {
    "event_id": "E168",
    "family": "summ",
    "from_version": "XSum",
    "to_version": "SEAHORSE",
    "date": "2023",
    "capability_axis_change": "multilingual",
    "morphology_change": "multilingual summarization eval",
    "saturation_driver": "english-only_narrow",
    "source_url": "https://arxiv.org/pdf/2210.17378"
  },
  {
    "event_id": "E169",
    "family": "graph",
    "from_version": "NLGraph",
    "to_version": "GraphInstruct",
    "date": "2024",
    "capability_axis_change": "cot_comprehensive",
    "morphology_change": "most comprehensive +chain-of-thought",
    "saturation_driver": "no_reasoning-path",
    "source_url": "https://arxiv.org/html/2403.04483v3"
  },
  {
    "event_id": "E170",
    "family": "graph",
    "from_version": "NLGraph",
    "to_version": "GraphArena",
    "date": "2024",
    "capability_axis_change": "realworld_harder",
    "morphology_change": "real-world graphs harder problems",
    "saturation_driver": "synthetic_small-scale",
    "source_url": "https://arxiv.org/html/2407.00379v1"
  },
  {
    "event_id": "E171",
    "family": "graph",
    "from_version": "GraphWiz",
    "to_version": "GraphWiz-corrected",
    "date": "2025",
    "capability_axis_change": "none",
    "morphology_change": "rectify Hamilton/Subgraph test errors",
    "saturation_driver": "test-set_errors",
    "source_url": "https://arxiv.org/html/2509.24260"
  },
  {
    "event_id": "E172",
    "family": "graph",
    "from_version": "NLGraph",
    "to_version": "GraphWiz",
    "date": "2024",
    "capability_axis_change": "instruction_tuning",
    "morphology_change": "explicit reasoning paths",
    "saturation_driver": "answer-only_shallow",
    "source_url": "https://graph-wiz.github.io/"
  },
  {
    "event_id": "E173",
    "family": "asr",
    "from_version": "LibriSpeech",
    "to_version": "FLEURS",
    "date": "2022",
    "capability_axis_change": "multilingual",
    "morphology_change": "102 languages parallel speech",
    "saturation_driver": "english-only_narrow",
    "source_url": "https://arxiv.org/pdf/2205.12446"
  },
  {
    "event_id": "E174",
    "family": "asr",
    "from_version": "LibriSpeech",
    "to_version": "Loquacious",
    "date": "2025",
    "capability_axis_change": "realistic_diverse",
    "morphology_change": "25k hrs diverse accents noisy spontaneous",
    "saturation_driver": "clean-read_saturated",
    "source_url": "https://arxiv.org/html/2505.21578v1"
  },
  {
    "event_id": "E175",
    "family": "asr",
    "from_version": "FLEURS",
    "to_version": "XTREME-S",
    "date": "2022",
    "capability_axis_change": "cross_lingual_suite",
    "morphology_change": "Fleurs+MLS+VoxPopuli 100+ langs",
    "saturation_driver": "single-corpus_narrow",
    "source_url": "https://arxiv.org/pdf/2203.10752"
  },
  {
    "event_id": "E176",
    "family": "asr",
    "from_version": "CommonVoice",
    "to_version": "CommonVoice-versioned",
    "date": "2021",
    "capability_axis_change": "none",
    "morphology_change": "periodic versioned snapshots fresh",
    "saturation_driver": "static_outdated",
    "source_url": "https://arxiv.org/pdf/2409.12042"
  },
  {
    "event_id": "E177",
    "family": "translation",
    "from_version": "FLORES-v1",
    "to_version": "FLORES-101",
    "date": "2021",
    "capability_axis_change": "scale_languages",
    "morphology_change": "101 languages from 2 pairs",
    "saturation_driver": "limited_languages",
    "source_url": "https://arxiv.org/pdf/2407.05975"
  },
  {
    "event_id": "E178",
    "family": "translation",
    "from_version": "FLORES-101",
    "to_version": "FLORES-200",
    "date": "2022",
    "capability_axis_change": "scale_languages",
    "morphology_change": "204 languages NLLB",
    "saturation_driver": "limited_languages",
    "source_url": "https://www.emergentmind.com/topics/flores-benchmark"
  },
  {
    "event_id": "E179",
    "family": "translation",
    "from_version": "FLORES-200",
    "to_version": "FLORES-plus",
    "date": "2024",
    "capability_axis_change": "community_validated",
    "morphology_change": "200+ langs multi-ref rigorous validation",
    "saturation_driver": "validation_quality",
    "source_url": "https://aclanthology.org/2024.wmt-1.41.pdf"
  },
  {
    "event_id": "E180",
    "family": "translation",
    "from_version": "WMT",
    "to_version": "WMT24-plus-plus",
    "date": "2025",
    "capability_axis_change": "harder_expand",
    "morphology_change": "55 languages harder",
    "saturation_driver": "saturation_narrow-band",
    "source_url": "https://arxiv.org/html/2605.28315"
  },
  {
    "event_id": "E181",
    "family": "translation",
    "from_version": "WMT",
    "to_version": "NTREX-128",
    "date": "2022",
    "capability_axis_change": "news_domain",
    "morphology_change": "128 languages news domain",
    "saturation_driver": "wmt19_limited",
    "source_url": "https://aclanthology.org/2022.sumeval-1.4.pdf"
  },
  {
    "event_id": "E182",
    "family": "tom",
    "from_version": "ToM-bAbi",
    "to_version": "ToMi",
    "date": "2019",
    "capability_axis_change": "procedural_variety",
    "morphology_change": "procedural narratives systematic sweep",
    "saturation_driver": "template_pattern-learning",
    "source_url": "https://arxiv.org/pdf/2310.15421"
  },
  {
    "event_id": "E183",
    "family": "tom",
    "from_version": "ToMi",
    "to_version": "FANToM",
    "date": "2023",
    "capability_axis_change": "interactive_dialogue",
    "morphology_change": "info-asymmetric conversational illusory-ToM",
    "saturation_driver": "passive-narrative_shortcut",
    "source_url": "https://arxiv.org/pdf/2310.15421"
  },
  {
    "event_id": "E184",
    "family": "tom",
    "from_version": "ToMi",
    "to_version": "Hi-ToM",
    "date": "2023",
    "capability_axis_change": "higher_order",
    "morphology_change": "4th-order belief reasoning",
    "saturation_driver": "first-order_too_easy",
    "source_url": "https://arxiv.org/html/2410.06195"
  },
  {
    "event_id": "E185",
    "family": "tom",
    "from_version": "ToMi",
    "to_version": "OpenToM",
    "date": "2024",
    "capability_axis_change": "broader_taxonomy",
    "morphology_change": "percepts/desires/emotions diverse",
    "saturation_driver": "false-belief-only_narrow",
    "source_url": "https://www.researchgate.net/publication/384217208_OpenToM"
  },
  {
    "event_id": "E186",
    "family": "tom",
    "from_version": "ToMi",
    "to_version": "ToMBench",
    "date": "2024",
    "capability_axis_change": "comprehensive",
    "morphology_change": "31 social cognition abilities 8 tasks",
    "saturation_driver": "fragmented_narrow",
    "source_url": "https://www.researchgate.net/publication/384204964_ToMBench"
  },
  {
    "event_id": "E187",
    "family": "tom",
    "from_version": "ToMi",
    "to_version": "MMToM-QA",
    "date": "2024",
    "capability_axis_change": "multimodal",
    "morphology_change": "multi-modal multi-agent ToM",
    "saturation_driver": "text-only_narrow",
    "source_url": "https://arxiv.org/pdf/2408.12574"
  },
  {
    "event_id": "E188",
    "family": "tom",
    "from_version": "ToMi",
    "to_version": "XToM",
    "date": "2025",
    "capability_axis_change": "multilingual",
    "morphology_change": "multilingual theory of mind",
    "saturation_driver": "english-only_narrow",
    "source_url": "https://arxiv.org/pdf/2506.02461"
  },
  {
    "event_id": "E189",
    "family": "tom",
    "from_version": "ToMi",
    "to_version": "ExploreToM",
    "date": "2025",
    "capability_axis_change": "adversarial",
    "morphology_change": "LLM adversarial data generation",
    "saturation_driver": "memorized_contamination",
    "source_url": "https://arxiv.org/html/2410.06195"
  }
];
